FROM golang:1.23.1

WORKDIR /usr/src/app

RUN go install github.com/air-verse/air@latest \
  &&  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
  &&  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

RUN sudo apt install protobuf-compiler

COPY . .
RUN go mod tidy
